drivers: c2k_usb: use bool for one-bit wide bit-field
../drivers/misc/mediatek/c2k_usb/f_rawbulk.c:336:16: error: implicit truncation from 'int' to a one-bit wide bit-field changes value from 1 to -1 [-Werror,-Wsingle-bit-bitfield-constant-conversion]
        fn->activated = 1;
                      ^ ~
../drivers/misc/mediatek/c2k_usb/f_rawbulk.c:381:19: error: implicit truncation from 'int' to a one-bit wide bit-field changes value from 1 to -1 [-Werror,-Wsingle-bit-bitfield-constant-conversion]
                fn->initialized = 1;
                                ^ ~
  CC      drivers/misc/mediatek/base/power/eemgpu_v2/mt6893/mtk_eemgpu_platform.o
../drivers/misc/mediatek/c2k_usb/f_rawbulk.c:461:19: error: implicit truncation from 'int' to a one-bit wide bit-field changes value from 1 to -1 [-Werror,-Wsingle-bit-bitfield-constant-conversion]
                fn->initialized = 1;
                                ^ ~
3 errors generated.

Change-Id: I75bfa3859fda063095b545fed32ea5195deb0a4d
Signed-off-by: CloudedQuartz <ayan.pande06@gmail.com>
(cherry picked from commit 287e936662b6cef47b2e5501d0e8f496d3ae9e23)