drivers: gpu: midgard: Drop redefinition of `__poll_t`
- Fixes :-

../drivers/misc/mediatek/gpu/gpu_mali/mali_bifrost/mali-r25p0/drivers/gpu/arm/midgard/mali_kbase_kinstr_jm.c:53:22: error: redefinition of typedef '__poll_t' is a C11 feature [-Werror,-Wtypedef-redefinition]
   53 | typedef unsigned int __poll_t;
      |                      ^
../include/uapi/linux/types.h:55:18: note: previous definition is here
   55 | typedef unsigned __poll_t;
      |                  ^
1 error generated.

Signed-off-by: Debayan Kar <kardebayan3@gmail.com>
(cherry picked from commit 1ff7bf3a4a5b2351919376ed08d8ac5c660ad838)
(cherry picked from commit 0a996b3c6e4e3b01138bde82531d9e3bf3c2742a)
(cherry picked from commit a9800bb9e47b4a581b35ff0a3e5ec9a5752d579d)